// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: envelope/envelope.proto

package envelope

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Envelope) Validate() error {
	if this.Deadline != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Deadline); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Deadline", err)
		}
	}
	return nil
}
