// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: erc20_utxo/service/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *NameResponse) Validate() error {
	return nil
}
func (this *SymbolResponse) Validate() error {
	return nil
}
func (this *DecimalsResponse) Validate() error {
	return nil
}
func (this *TotalSupplyResponse) Validate() error {
	return nil
}
