// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: testdata/serialize.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Payment) Validate() error {
	return nil
}
