name: Go Quality

on: [ push, pull_request ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'

      - name: Check out code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: go test -v -covermode=count -coverprofile=coverage.out.tmp ./...
      - name: Strip generated code
        run: cat coverage.out.tmp | grep -v ".pb.go" | grep -v ".pb.cc.go" | grep -v ".pb.gw.go" > coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.5
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov